# Generated by Django 3.0 on 2021-06-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210602_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answers',
        ),
    ]
