# Generated by Django 3.0 on 2021-06-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quiz_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='enrollment_key',
            field=models.CharField(default='none', max_length=16),
        ),
    ]
